create table Person
(
    id    serial,
    name  varchar,
    age   int,
    email varchar
);

create table Person
(
    id    int GENERATED BY DEFAULT AS IDENTITY ,
    name  varchar,
    age   int,
    email varchar
);

create table Person
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar NOT NULL,
    age   int check ( age > 0 ),
    email varchar UNIQUE
);
insert into person(name, age, email) VALUES ('Ted', 44, 'School@mail.ru');
insert into person(name, age, email) VALUES ('Sonya', 15, 'Cathc@mail.ru');
insert into person(name, age, email) VALUES ('Marya', 39, 'Sotki@gmail.ru');
insert into person(name, age, email) VALUES ('Med', 15, 'soroka@mail.ru');

insert into person
values (2, 'Sonya', 15, 'Cathc@mail.ru');
insert into person
values (3, 'Marya', 39, 'Sotki@gmail.ru');
insert into person
values (4, 'Ted', 44, 'School@mail.ru');

select *
from Person;

drop table Person;

create sequence my_sequence;

select nextval('my_sequence');
drop sequence my_sequence;